spring:
  profiles:
    include: local          # application-local.yml(개인 설정)을 함께 읽음
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always          # 서버 시작 때마다 schema.sql, data.sql 실행 (개발 중)
      encoding: UTF-8
server:
  servlet:
    session:
      timeout: 60m